# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3ed4320cb4b06787c884b378eb6c041258ac4bf1854d055f0b9cc3928d85627deffd383fe168cd6e91b7c7af4507bd40da9ad9a47b054d293398d5823016c48

test:
  secret_key_base: 37d93d0472894e5d65a255b9250a81649d351f454be7eb107e2064b9a97eff48aabbdc00ad8a0c3a66fe64bfa3d045cbbb67fe907f2dd221c39a2cc50bcfb2d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
